---
meta:
  author: shenfei
  homepage: http://isux.tencent.com
  email: isux@qq.com
  twitter: http://t.qq.com/isux
  github: https://github.com/qianduan/tencent.font
  license: SIL
  license_url: http://scripts.sil.org/OFL

  css_prefix: "icon-"
  columns: 4

#transform:
#  baseline: 0.4
#  rescale: 2.4

font:
  version: "1.0"

  # use !!!small!!! letters a-z, or Opera will fail under OS X
  # fontname will be also used as file name.
  fontname: tencent

  fullname: tencent
  familyname: tencent

  copyright: Copyright (C) 2013 by isux qzone team

  ascent: 850
  descent: 150
  weight: Normal


glyphs:

  -
    css: qq-com
    code: 0xf800
    uid: 006675451405d2ccc683b4608aec70dd 
    meta:
      author: isux
      email: isux@qq.com
    search: [qq,qq.com]
  -
    css: qzone
    code: 0xe801
    uid: c5ea7f98eb5ed86d39f4677baadbb6a7
    meta:
      author: isux
      email: isux@qq.com
    search: [logo, qzone, isux]
  -
    css: qzone2
    code: 0xf802
    uid: e8a8af4d484f8a13f1b2a2e25177f099 
    meta:
      author: isux
      email: isux@qq.com
    search: [logo, qzone, isux]
  -
    css: qzone3
    code: 0xf803
    uid: 79f3f2a63fa7faa3499ab7d27be874de 
    meta:
      author: isux
      email: isux@qq.com
    search: [logo, qzone, isux]
  -
    css: qzone-lock
    code: 0xf804
    uid: 1953ac5f1f884e8b56b349222bca95d9 
    meta:
      author: isux
      email: isux@qq.com
    search: [logo, qzone, isux]
  -
    css: qzone-disabled
    code: 0xf805
    uid: f7ea69a750daee6748ca84f653a399f4 
    meta:
      author: isux
      email: isux@qq.com
    search: [logo, qzone, isux]
  -
    css: isux
    code: 0xe806
    uid: 56051ec6f85f63e8f0f40a8d4875e876
    meta:
      author: isux
      email: isux@qq.com
    search: [logo, qzone, isux]
  -
    css: weibo
    code: 0xf807
    uid: 6e53988bff32068977a1204f1fd627a1 
    meta:
      author: isux
      email: isux@qq.com
    search: [weibo,tencent]
  -
    css: weibo2
    code: 0xf808
    uid: 9c963aeab2cd4a7435b5639833f652fa 
    meta:
      author: isux
      email: isux@qq.com
    search: [weibo,tencent]
  -
    css: at
    code: 0xf809
    uid: ed5644aab0bff71e6db74ac15f39f245 
    meta:
      author: isux
      email: isux@qq.com
    search: [at,tencent]
  -
    css: add
    code: 0xf80a
    uid: 3e58ddc8998807b91c809cc75626a01b 
    meta:
      author: isux
      email: isux@qq.com
    search: [add,tencent]
  -
    css: search
    code: 0xf80b
    uid: a8223e1b949d855c4ffe3eae7c346d4d 
    meta:
      author: isux
      email: isux@qq.com
    search: [search,tencent]
  -
    css: setting
    code: 0xf80c
    uid: 0abb66778c6bc4ecf94fdc2802e6ab7a 
    meta:
      author: isux
      email: isux@qq.com
    search: [setting,tencent]
  -
    css: clothes
    code: 0xf80d
    uid: 7bcbdd9b47d7bb15cdad8900601f0c0f 
    meta:
      author: isux
      email: isux@qq.com
    search: [clothes,tencent]
  -
    css: close
    code: 0xf80e
    uid: 45bbde8e88e618419a3611d01a8475fb 
    meta:
      author: isux
      email: isux@qq.com
    search: [close,tencent]
  -
    css: delete
    code: 0xf80f
    uid: a99a22a32034bab4c50c8500c7cce31f 
    meta:
      author: isux
      email: isux@qq.com
    search: [delete,tencent]
  -
    css: person
    code: 0xf810
    uid: 69b994c5d51aaa6cad8a57604f8141c5 
    meta:
      author: isux
      email: isux@qq.com
    search: [person,tencent]
  -
    css: persons
    code: 0xf811
    uid: 91e3a9228759d2aaa2dd70d9f66e38e1 
    meta:
      author: isux
      email: isux@qq.com
    search: [person,tencent]
  -
    css: persons-disabled
    code: 0xf812
    uid: f0a193e2a64594d486130687056b7a38 
    meta:
      author: isux
      email: isux@qq.com
    search: [person,disabled,tencent]
  -
    css: male
    code: 0xf813
    uid: 3470b9bc220a42cb475ef076e6b551ab 
    meta:
      author: isux
      email: isux@qq.com
    search: [male,tencent]
  -
    css: female
    code: 0xf814
    uid: 69806d41b9907f8312ec4036d50e4273 
    meta:
      author: isux
      email: isux@qq.com
    search: [female,tencent]
  -
    css: write
    code: 0xf815
    uid: 084d8b3657f7fd6c0da3c91d0448e9d5 
    meta:
      author: isux
      email: isux@qq.com
    search: [write,tencent]
  -
    css: write2
    code: 0xf816
    uid: 29d26f42c39da97999ef84ddd0adf03c 
    meta:
      author: isux
      email: isux@qq.com
    search: [write,tencent]
  -
    css: reply
    code: 0xf817
    uid: cc12abec2b2044f9f64ef2402527d3b5 
    meta:
      author: isux
      email: isux@qq.com
    search: [reply,tencent]
  -
    css: reply2
    code: 0xf818
    uid: 372061bff5efc663a28f91b872240fbc 
    meta:
      author: isux
      email: isux@qq.com
    search: [reply,tencent]
  -
    css: comment
    code: 0xf819
    uid: 34d508cfc9cc2b7b79731d63dd0e1c70 
    meta:
      author: isux
      email: isux@qq.com
    search: [comment,tencent]
  -
    css: chat
    code: 0xf81a
    uid: a540be86a59b6edecef62752ad24d1f0 
    meta:
      author: isux
      email: isux@qq.com
    search: [chat,tencent]
  -
    css: retweet
    code: 0xf81b
    uid: 2257d21f245a5f423e1de0aefb5ffd84 
    meta:
      author: isux
      email: isux@qq.com
    search: [retweet,tencent]
  -
    css: microphone
    code: 0xf81c
    uid: da88c36949fef4035e74bae90fc153e0 
    meta:
      author: isux
      email: isux@qq.com
    search: [microphone,tencent]
  -
    css: microphone-disabled
    code: 0xf81d
    uid: 71f7fcda08a6ccdd21fa50a06a347cf4 
    meta:
      author: isux
      email: isux@qq.com
    search: [microphone,tencent]
  -
    css: sound
    code: 0xf826
    uid: edf3f468b175ab3b4dd31cd4d0a5865c 
    meta:
      author: isux
      email: isux@qq.com
    search: [sound,tencent]
  -
    css: camera
    code: 0xf81e
    uid: c9e7ad2c8e3dc3b67b5a4793ebbe3de1 
    meta:
      author: isux
      email: isux@qq.com
    search: [camera,tencent]
  -
    css: camera2
    code: 0xf81f
    uid: f7e63094c046bfe85ba8ab5bdbf7096c 
    meta:
      author: isux
      email: isux@qq.com
    search: [camera,tencent]
  -
    css: camera3
    code: 0xf820
    uid: 63bea61945057894406e5dbb308d9e74 
    meta:
      author: isux
      email: isux@qq.com
    search: [camera,tencent]
  -
    css: camera-disabled
    code: 0xf821
    uid: 7d21144e6042be6f68c61ce3900d0c65 
    meta:
      author: isux
      email: isux@qq.com
    search: [camera,disabled,tencent]
  -
    css: emotion
    code: 0xf822
    uid: c41b6732303cf6097b72764baff76286 
    meta:
      author: isux
      email: isux@qq.com
    search: [emotion,tencent]
  -
    css: emotion-add
    code: 0xf823
    uid: 0a21fcb6ecaf4956fbcc238ef592d65a 
    meta:
      author: isux
      email: isux@qq.com
    search: [emotion,add,tencent]
  -
    css: emotion-favorate
    code: 0xf824
    uid: e862f50ca71b0389f7ed7bc769eac8c4 
    meta:
      author: isux
      email: isux@qq.com
    search: [emotion,favorate,tencent]
  -
    css: heart
    code: 0xf825
    uid: 79d55f7d824c86104a4b093caba4a8e2 
    meta:
      author: isux
      email: isux@qq.com
    search: [heart,tencent]
  -
    css: share
    code: 0xf827
    uid: 081537f722bbdbc1b096415591b930f6 
    meta:
      author: isux
      email: isux@qq.com
    search: [share,tencent]
  -
    css: save
    code: 0xf828
    uid: aebce74b01075155f662a1b1c4542062 
    meta:
      author: isux
      email: isux@qq.com
    search: [save,tencent]
  -
    css: home
    code: 0xf829
    uid: 8a44b2e52359b510be2381f03ca679cb 
    meta:
      author: isux
      email: isux@qq.com
    search: [home,tencent]
  -
    css: profile
    code: 0xf82a
    uid: c083e154053d0c8ac16a2f213609d51d 
    meta:
      author: isux
      email: isux@qq.com
    search: [profile,tencent]
  -
    css: timing
    code: 0xf82b
    uid: bd5246fa15a7a0aa667ade9118e6eb4f 
    meta:
      author: isux
      email: isux@qq.com
    search: [timing,tencent]
  -
    css: time
    code: 0xf82c
    uid: baae97ed811994e116538a08a1a0c733 
    meta:
      author: isux
      email: isux@qq.com
    search: [time,tencent]
  -
    css: time2
    code: 0xf82d
    uid: a5ec1ebfa484a3f67f3beaf4ddd4ef71 
    meta:
      author: isux
      email: isux@qq.com
    search: [time,tencent]
  -
    css: countdown
    code: 0xf82e
    uid: 712860b4b37497154009f19f6e1c6c8a 
    meta:
      author: isux
      email: isux@qq.com
    search: [countdown,tencent]
  -
    css: plane
    code: 0xf82f
    uid: a5bb0e37dd683b881f654e7c7994fc41 
    meta:
      author: isux
      email: isux@qq.com
    search: [plane,tencent]
  -
    css: fullscreen
    code: 0xf830
    uid: 34495588058b4ed8086867c8629cb0cc 
    meta:
      author: isux
      email: isux@qq.com
    search: [fullscreen,tencent]
  -
    css: restore
    code: 0xf831
    uid: c8394c9fdc0ac94db106c730af80d981 
    meta:
      author: isux
      email: isux@qq.com
    search: [restore,tencent]
  -
    css: image
    code: 0xf832
    uid: 7047d50c147900b0263229723cf8dcac 
    meta:
      author: isux
      email: isux@qq.com
    search: [image,tencent]
  -
    css: graffiti
    code: 0xf833
    uid: ad31e700044e7e6396569ada7f1c28ce 
    meta:
      author: isux
      email: isux@qq.com
    search: [graffiti,tencent]
  -
    css: geolocation
    code: 0xf834
    uid: 233ae9c54d7bb6ff4697f03346d5ebd0 
    meta:
      author: isux
      email: isux@qq.com
    search: [location,geolocation,tencent]
  -
    css: keyboard
    code: 0xf835
    uid: 3cfc211e200de7512516b6ff6c3fe91d 
    meta:
      author: isux
      email: isux@qq.com
    search: [keyboard,tencent]
  -
    css: open-folder
    code: 0xf836
    uid: 7a081631ff7de56c6ec1415ff46fe1d2 
    meta:
      author: isux
      email: isux@qq.com
    search: [open,folder,tencent]
